sudo: required 
services: 
  - docker 

before_install:
  - docker build -t samraola30/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samraola30/react-test npm test -- --coverage   

after_success: 
  - docker build -t samraola30/multi-client ./client 
  - docker build -t samraola30/multi-nginx ./nginx 
  - docker build -t samraola30/multi-server ./server 
  - docker build -t samraola30/multi-worker ./worker 
 # log in to the docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  - docker push samraola30/multi-client
  - docker push samraola30/multi-nginx
  - docker push samraola30/multi-server 
  - docker push samraola30/multi-worker 